-- Generated from txt_catalogs; table names from column 'Ký hiệu danh mục'
-- Structure only (CREATE TABLE)

-- From 001_CAP-KHEN-THUONG.txt
CREATE TABLE CAP_KHEN_THUONG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 002_CHU-SO-HUU.txt
CREATE TABLE CHU_SO_HUU (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 003_CHUC-DANH-GIANG-VIEN.txt
CREATE TABLE CHUC_DANH_GIANG_VIEN (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 004_CHUC-DANH-NGHE-NGHIEP-VIEN-CHUC-GIANG-DAY-TRONG-CO-SO-GIAO-DUC-DAI-HOC-CONG-LAP.txt
CREATE TABLE CHUC_DANH_NGHE_NGHIEP_VIEN_CHUC_GIANG_DAY_TRONG_CO_SO_GIAO_DUC_DAI_HOC_CONG_LAP (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 005_CHUC-DANH-HOI-DONG-BAN.txt
CREATE TABLE CHUC_DANH_HOI_DONG_BAN (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 006_CHUC-DANH-NGHIEN-CUU-KHOA-HOC.txt
CREATE TABLE CHUC_DANH_NGHIEN_CUU_KHOA_HOC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 007_CHUC-VU.txt
CREATE TABLE CHUC_VU (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 008_DAN-TOC.txt
CREATE TABLE DAN_TOC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 009_DANH-HIEU-THI-DUA.txt
CREATE TABLE DANH_HIEU_THI_DUA (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 010_LOAI-DAU-MOI-LIEN-HE.txt
CREATE TABLE LOAI_DAU_MOI_LIEN_HE (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 011_DOI-TUONG-TUYEN-SINH-DAU-VAO.txt
CREATE TABLE DOI_TUONG_TUYEN_SINH_DAU_VAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 012_DOI-TUONG-CHINH-SACH.txt
CREATE TABLE DOI_TUONG_CHINH_SACH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 013_DON-VI-CAP-BANG.txt
CREATE TABLE DON_VI_CAP_BANG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 014_GIOI-TINH.txt
CREATE TABLE GIOI_TINH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 015_HINH-THUC-BO-NHIEM.txt
CREATE TABLE HINH_THUC_BO_NHIEM (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 016_HINH-THUC-CHUYEN-GIAO-CONG-NGHE.txt
CREATE TABLE HINH_THUC_CHUYEN_GIAO_CONG_NGHE (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 017_HINH-THUC-DAO-TAO.txt
CREATE TABLE HINH_THUC_DAO_TAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 018_LOAI-HOP-DONG.txt
CREATE TABLE LOAI_HOP_DONG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 019_HINH-THUC-HOP-TAC-QUOC-TE.txt
CREATE TABLE HINH_THUC_HOP_TAC_QUOC_TE (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 020_HINH-THUC-KHEN-THUONG.txt
CREATE TABLE HINH_THUC_KHEN_THUONG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 021_HINH-THUC-SO-HUU.txt
CREATE TABLE HINH_THUC_SO_HUU (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 022_HINH-THUC-THANH-LAP.txt
CREATE TABLE HINH_THUC_THANH_LAP (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 023_HINH-THUC-TUYEN-DUNG.txt
CREATE TABLE HINH_THUC_TUYEN_DUNG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 024_HOC-CHE-DAO-TAO.txt
CREATE TABLE HOC_CHE_DAO_TAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 025_CHUC-DANH-KHOA-HOC.txt
CREATE TABLE CHUC_DANH_KHOA_HOC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 027_KET-QUA-KIEM-DINH.txt
CREATE TABLE KET_QUA_KIEM_DINH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 028_KHOI-NGANH.txt
CREATE TABLE KHOI_NGANH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 029_KHU-VUC.txt
CREATE TABLE KHU_VUC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 030_KHUNG-NANG-LUC-NGOAI-NGU.txt
CREATE TABLE KHUNG_NANG_LUC_NGOAI_NGU (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 031_LINH-VUC-DE-TAI.txt
CREATE TABLE LINH_VUC_DE_TAI (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 032_LOAI-SACH-TAP-CHI.txt
CREATE TABLE LOAI_SACH_TAP_CHI (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 033_DANH-HIEU-VINH-DU-GIAI-THUONG.txt
CREATE TABLE DANH_HIEU_VINH_DU_GIAI_THUONG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 034_LOAI-CHUONG-TRINH-DAO-TAO.txt
CREATE TABLE LOAI_CHUONG_TRINH_DAO_TAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 035_LINH-VUC-NGHIEN-CUU.txt
CREATE TABLE LINH_VUC_NGHIEN_CUU (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 036_LOAI-CHUONG-TRINH-LIEN-KET-DAO-TAO.txt
CREATE TABLE LOAI_CHUONG_TRINH_LIEN_KET_DAO_TAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 037_LOAI-CONG-TRINH-KHAC.txt
CREATE TABLE LOAI_CONG_TRINH_KHAC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 038_LOAI-DE-TAI-KHOA-HOC.txt
CREATE TABLE LOAI_DE_TAI_KHOA_HOC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 039_LOAI-TAI-SAN-TRI-TUE.txt
CREATE TABLE LOAI_TAI_SAN_TRI_TUE (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 040_LOAI-GIANG-VIEN-QPAN.txt
CREATE TABLE LOAI_GIANG_VIEN_QPAN (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 041_LOAI-HINH-DAO-TAO.txt
CREATE TABLE LOAI_HINH_DAO_TAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 042_LOAI-HINH-TRUONG.txt
CREATE TABLE LOAI_HINH_TRUONG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 043_LOAI-KHUYET-TAT.txt
CREATE TABLE LOAI_KHUYET_TAT (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 044_LOAI-KY-LUAT.txt
CREATE TABLE LOAI_KY_LUAT (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 045_LOAI-LUU-HOC-SINH.txt
CREATE TABLE LOAI_LUU_HOC_SINH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 046_MUC-TIEU-NHIEM-VU-KHCN.txt
CREATE TABLE MUC_TIEU_NHIEM_VU_KHCN (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 047_LOAI-PHONG-THI-NGHIEM.txt
CREATE TABLE LOAI_PHONG_THI_NGHIEM (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 048_THAM-QUYEN-QUYET-DINH.txt
CREATE TABLE THAM_QUYEN_QUYET_DINH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 049_NGANH-CHUYEN-NGANH-CHUYEN-MON-DAO-TAO.txt
CREATE TABLE NGANH_CHUYEN_NGANH_CHUYEN_MON_DAO_TAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 050_NGANH-KINH-TE.txt
CREATE TABLE NGANH_KINH_TE (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 051_NGOAI-NGU.txt
CREATE TABLE NGOAI_NGU (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 052_NGUON-KINH-PHI.txt
CREATE TABLE NGUON_KINH_PHI (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 053_NGUON-VON-DAU-TU.txt
CREATE TABLE NGUON_VON_DAU_TU (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 054_NHOM-NGANH.txt
CREATE TABLE NHOM_NGANH (
  Ma VARCHAR(50),
  Ten VARCHAR(255),
  Ma_HEMIS VARCHAR(255)
);

-- From 055_PHAN-LOAI-CO-SO.txt
CREATE TABLE PHAN_LOAI_CO_SO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 056_PHUONG-THUC-KHEN-THUONG.txt
CREATE TABLE PHUONG_THUC_KHEN_THUONG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 057_TAP-CHI-KHOA-HOC-QUOC-TE.txt
CREATE TABLE TAP_CHI_KHOA_HOC_QUOC_TE (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 058_TINH-TP-MOI.txt
CREATE TABLE TINH_TP_MOI (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 059_TINH-TP-CU.txt
CREATE TABLE TINH_TP_CU (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 060_TINH-TRANG-CSVC.txt
CREATE TABLE TINH_TRANG_CSVC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 061_TRANG-THAI-TINH-TRANG-THUC-HIEN.txt
CREATE TABLE TRANG_THAI_TINH_TRANG_THUC_HIEN (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 062_TO-CHUC-KIEM-DINH.txt
CREATE TABLE TO_CHUC_KIEM_DINH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 063_TON-GIAO.txt
CREATE TABLE TON_GIAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 064_LOAI-TOT-NGHIEP.txt
CREATE TABLE LOAI_TOT_NGHIEP (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 065_TRANG-THAI-CAN-BO-TRANG-THAI-LAM-VIEC.txt
CREATE TABLE TRANG_THAI_CAN_BO_TRANG_THAI_LAM_VIEC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 066_TRANG-THAI-CHUONG-TRINH-DAO-TAO.txt
CREATE TABLE TRANG_THAI_CHUONG_TRINH_DAO_TAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 067_TRANG-THAI-HOC-VIEN-TRANG-THAI-HOC.txt
CREATE TABLE TRANG_THAI_HOC_VIEN_TRANG_THAI_HOC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 068_TINH-TRANG-HOP-DONG.txt
CREATE TABLE TINH_TRANG_HOP_DONG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 069_TRINH-DO-DAO-TAO-DAU-RA.txt
CREATE TABLE TRINH_DO_DAO_TAO_DAU_RA (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 070_TRINH-DO-DAO-TAO.txt
CREATE TABLE TRINH_DO_DAO_TAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 071_TRINH-DO-LY-LUAN-CHINH-TRI.txt
CREATE TABLE TRINH_DO_LY_LUAN_CHINH_TRI (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 072_TRINH-DO-QUAN-LY-NHA-NUOC.txt
CREATE TABLE TRINH_DO_QUAN_LY_NHA_NUOC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 073_TRINH-DO-TIN-HOC.txt
CREATE TABLE TRINH_DO_TIN_HOC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 074_VAI-TRO-LIEN-QUAN-CAN-BO-THAM-GIA-NCKH.txt
CREATE TABLE VAI_TRO_LIEN_QUAN_CAN_BO_THAM_GIA_NCKH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 075_VAI-TRO-TRONG-BAI-BAO.txt
CREATE TABLE VAI_TRO_TRONG_BAI_BAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 076_XA-PHUONG.txt
CREATE TABLE XA_PHUONG (
  Ma VARCHAR(50),
  Ten VARCHAR(255),
  Tinh VARCHAR(255)
);

-- From 077_LINH-VUC-DAO-TAO.txt
CREATE TABLE LINH_VUC_DAO_TAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 078_NGUON-KINH-PHI-LUU-HSSV-NUOC-NGOAI.txt
CREATE TABLE NGUON_KINH_PHI_LUU_HSSV_NUOC_NGOAI (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 079_NGUON-KINH-PHI-DE-AN-DU-AN-CHUONG-TRINH.txt
CREATE TABLE NGUON_KINH_PHI_DE_AN_DU_AN_CHUONG_TRINH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 080_NOI-DUNG-HOAT-DONG-VIET-NAM.txt
CREATE TABLE NOI_DUNG_HOAT_DONG_VIET_NAM (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 081_QUOC-GIA-QUOC-TICH-NUOC.txt
CREATE TABLE QUOC_GIA_QUOC_TICH_NUOC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 082_CAP-NHIEM-VU-KHCN.txt
CREATE TABLE CAP_NHIEM_VU_KHCN (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 083_BAC-LUONG.txt
CREATE TABLE BAC_LUONG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 084_HE-SO-LUONG.txt
CREATE TABLE HE_SO_LUONG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 085_DANH-GIA-CONG-CHUC-VIEN-CHUC.txt
CREATE TABLE DANH_GIA_CONG_CHUC_VIEN_CHUC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 086_HANG-THUONG-BINH.txt
CREATE TABLE HANG_THUONG_BINH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 087_GIA-DINH-CHINH-SACH.txt
CREATE TABLE GIA_DINH_CHINH_SACH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 088_TIENG-DAN-TOC.txt
CREATE TABLE TIENG_DAN_TOC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 089_TINH-TRANG-VIEC-LAM.txt
CREATE TABLE TINH_TRANG_VIEC_LAM (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 090_LOAI-HOC-BONG.txt
CREATE TABLE LOAI_HOC_BONG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 091_LOAI-PHONG-BAN-DON-VI.txt
CREATE TABLE LOAI_PHONG_BAN_DON_VI (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 092_CAP-HOI-NGHI.txt
CREATE TABLE CAP_HOI_NGHI (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 093_MA-NGACH-CHUC-DANH-NGHE-NGHIEP.txt
CREATE TABLE MA_NGACH_CHUC_DANH_NGHE_NGHIEP (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 094_HINH-THUC-THAM-GIA-GIANG-VIEN-CU-DI-DAO-TAO.txt
CREATE TABLE HINH_THUC_THAM_GIA_GIANG_VIEN_CU_DI_DAO_TAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 095_TINH-TRANG-GIANG-VIEN-CU-DI-DAO-TAO.txt
CREATE TABLE TINH_TRANG_GIANG_VIEN_CU_DI_DAO_TAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 096_NGUON-KINH-PHI-GIANG-VIEN-CU-DI-DAO-TAO.txt
CREATE TABLE NGUON_KINH_PHI_GIANG_VIEN_CU_DI_DAO_TAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 097_MUC-DICH-SU-DUNG-CSVC.txt
CREATE TABLE MUC_DICH_SU_DUNG_CSVC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 098_MUC-GIAI-THUONG.txt
CREATE TABLE MUC_GIAI_THUONG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 099_TINH-TRANG-THIET-BI.txt
CREATE TABLE TINH_TRANG_THIET_BI (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 100_THANH-VIEN-NHOM-NGHIEN-CUU-MANH.txt
CREATE TABLE THANH_VIEN_NHOM_NGHIEN_CUU_MANH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 101_TINH-TRANG-NHIEM-VU-KHCN.txt
CREATE TABLE TINH_TRANG_NHIEM_VU_KHCN (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 102_QUAN-HAM.txt
CREATE TABLE QUAN_HAM (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 103_LOAI-BOI-DUONG.txt
CREATE TABLE LOAI_BOI_DUONG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 104_PHAN-LOAI-NHIEM-VU-KHCN.txt
CREATE TABLE PHAN_LOAI_NHIEM_VU_KHCN (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 105_XEP-HANG-TAP-CHI.txt
CREATE TABLE XEP_HANG_TAP_CHI (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 106_XEP-HANG-Q.txt
CREATE TABLE XEP_HANG_Q (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 107_LOAI-NHIEM-VU-BVMT.txt
CREATE TABLE LOAI_NHIEM_VU_BVMT (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 108_LOAI-GIAI-THUONG-KHCN.txt
CREATE TABLE LOAI_GIAI_THUONG_KHCN (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 109_HINH-THUC-DOANH-NGHIEP-KHCN.txt
CREATE TABLE HINH_THUC_DOANH_NGHIEP_KHCN (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 110_VAI-TRO-THAM-GIA-CONG-TAC.txt
CREATE TABLE VAI_TRO_THAM_GIA_CONG_TAC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 111_VI-TRI-LAM-VIEC.txt
CREATE TABLE VI_TRI_LAM_VIEC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 112_MUC-DICH-SU-DUNG-DAT-DAI.txt
CREATE TABLE MUC_DICH_SU_DUNG_DAT_DAI (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 113_HINH-THUC-SU-DUNG-DAT.txt
CREATE TABLE HINH_THUC_SU_DUNG_DAT (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 114_TRANG-THAI-PHONG-BAN.txt
CREATE TABLE TRANG_THAI_PHONG_BAN (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 115_TRANG-THAI-CO-SO-GIAO-DUC.txt
CREATE TABLE TRANG_THAI_CO_SO_GIAO_DUC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 116_LOAI-LIEN-KET-CO-SO-DAO-TAO.txt
CREATE TABLE LOAI_LIEN_KET_CO_SO_DAO_TAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 117_TRANG-THAI-HOI-DONG-BAN-GIAM-HIEU.txt
CREATE TABLE TRANG_THAI_HOI_DONG_BAN_GIAM_HIEU (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 118_LOAI-KHEN-THUONG.txt
CREATE TABLE LOAI_KHEN_THUONG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 119_TRANG-THAI-VAN-BAN-TRIEN-KHAI-QUYEN-TU-CHU-THEO-LUAT-GDDH.txt
CREATE TABLE TRANG_THAI_VAN_BAN_TRIEN_KHAI_QUYEN_TU_CHU_THEO_LUAT_GDDH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 120_PHAN-LOAI-GIANG-VIEN-DAO-TAO-QPAN.txt
CREATE TABLE PHAN_LOAI_GIANG_VIEN_DAO_TAO_QPAN (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 121_PHAN-LOAI-NGUOI-HOC.txt
CREATE TABLE PHAN_LOAI_NGUOI_HOC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 122_TINH-TRANG-SU-DUNG-CONG-TRINH-CSVC.txt
CREATE TABLE TINH_TRANG_SU_DUNG_CONG_TRINH_CSVC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 123_PHAN-LOAI-PHONG-HOC-GIANG-DUONG-HOI-TRUONG.txt
CREATE TABLE PHAN_LOAI_PHONG_HOC_GIANG_DUONG_HOI_TRUONG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 124_LOAI-PHONG-HOC.txt
CREATE TABLE LOAI_PHONG_HOC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 125_PHAN-LOAI-DU-AN-CHUONG-TRINH.txt
CREATE TABLE PHAN_LOAI_DU_AN_CHUONG_TRINH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 126_LOAI-QUYET-DINH-CAP-PHEP-CHUONG-TRINH-DAO-TAO.txt
CREATE TABLE LOAI_QUYET_DINH_CAP_PHEP_CHUONG_TRINH_DAO_TAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 127_NGUOI-HOC-NAM.txt
CREATE TABLE NGUOI_HOC_NAM (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 128_HINH-THUC-KY-LUAT.txt
CREATE TABLE HINH_THUC_KY_LUAT (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 129_PHAN-LOAI-TO-CHUC-HOP-TAC-DOANH-NGHIEP.txt
CREATE TABLE PHAN_LOAI_TO_CHUC_HOP_TAC_DOANH_NGHIEP (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 130_PHAN-LOAI-DOAN-CONG-TAC.txt
CREATE TABLE PHAN_LOAI_DOAN_CONG_TAC (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 131_DANG-TAI-LIEU.txt
CREATE TABLE DANG_TAI_LIEU (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 132_PHAN-LOAI-BAI-BAO.txt
CREATE TABLE PHAN_LOAI_BAI_BAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 133_PHAN-LOAI-DOI-TUONG-THAM-GIA-NCKH.txt
CREATE TABLE PHAN_LOAI_DOI_TUONG_THAM_GIA_NCKH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 134_TRANG-THAI-NGANH-DAO-TAO.txt
CREATE TABLE TRANG_THAI_NGANH_DAO_TAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 135_TRANG-THAI-TAI-SAN.txt
CREATE TABLE TRANG_THAI_TAI_SAN (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 136_PHAN-LOAI-HOAT-DONG-TAI-CHINH.txt
CREATE TABLE PHAN_LOAI_HOAT_DONG_TAI_CHINH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 137_PHAN-LOAI-THU-CHI.txt
CREATE TABLE PHAN_LOAI_THU_CHI (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 138_HINH-THUC-TUYEN-SINH.txt
CREATE TABLE HINH_THUC_TUYEN_SINH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 139_KHU-VUC-TUYEN-SINH.txt
CREATE TABLE KHU_VUC_TUYEN_SINH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 140_DOI-TUONG-UU-TIEN.txt
CREATE TABLE DOI_TUONG_UU_TIEN (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 141_LOAI-CO-SO-DAO-TAO.txt
CREATE TABLE LOAI_CO_SO_DAO_TAO (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 142_LOAI-VAN-BAN-TRIEN-KHAI-QUYEN-TU-CHU-THEO-LUAT-GDDH.txt
CREATE TABLE LOAI_VAN_BAN_TRIEN_KHAI_QUYEN_TU_CHU_THEO_LUAT_GDDH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 143_CAY-TO-CHUC-DHQGHN.txt
CREATE TABLE CAY_TO_CHUC_DHQGHN (
  Ma VARCHAR(50) PRIMARY KEY,
  Ten VARCHAR(255),
  Don_vi_cha VARCHAR(50) REFERENCES CAY_TO_CHUC_DHQGHN(Ma)
);

-- From 144_DANH-GIA-KET-QUA-NHIEM-VU-KHCN.txt
CREATE TABLE DANH_GIA_KET_QUA_NHIEM_VU_KHCN (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 145_CO-QUAN-CHU-QUAN.txt
CREATE TABLE CO_QUAN_CHU_QUAN (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 146_LOAI-QUYET-DINH.txt
CREATE TABLE LOAI_QUYET_DINH (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 147_LOAI-HOI-DONG.txt
CREATE TABLE LOAI_HOI_DONG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 148_NGUON-KINH-PHI-DAT-TAI.txt
CREATE TABLE NGUON_KINH_PHI_DAT_TAI (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 149_NGUON-KINH-PHI-KHCN.txt
CREATE TABLE NGUON_KINH_PHI_KHCN (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 150_LOAI-KY-YEU.txt
CREATE TABLE LOAI_KY_YEU (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 151_LOAI-GIAI-THUONG.txt
CREATE TABLE LOAI_GIAI_THUONG (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 152_SAN-PHAM-DE-TAI.txt
CREATE TABLE SAN_PHAM_DE_TAI (
  Ma VARCHAR(50),
  Ten VARCHAR(255)
);

-- From 153_XA-PHUONG-CU.txt
CREATE TABLE XA_PHUONG_CU (
  Ma VARCHAR(50),
  Ten VARCHAR(255),
  Huyen VARCHAR(255),
  Tinh VARCHAR(255)
);
